---
- hosts: webservers
  become: yes
  tasks:
  - name: Install the webserjava on Ubuntu
    apt:
     name: "{{myjavainstall}}"
     state: present

  - name: Please Start the Webserver on Ubuntu
    service:
      name: apache2
      state: started